### ISSUE TITLE
Required Courses List

### ISSUE THREAD

**Issue by td-locus-user** [td-locus-user/TOPS#2]
Please add below the courses that you would like to purchase/download (Course Name - Link):

Seems, most of the Udemy courses are available for free on https://ftuforum.com/

So, I would recommend you to review the above site before posting a comment. Even if you post a link, it will definitely be reviewed and assessed before a purchase is made.

Overall budget for this month is: `5000/-`

Thanks for your cooperation.

**Comment by UKN619** [comment]
Complete Python bootcamp-https://www.udemy.com/share/100058/

**Comment by devanshsrivastava** [comment]
The Ultimate Hands-On Hadoop  : https://www.udemy.com/the-ultimate-hands-on-hadoop-tame-your-big-data/

**Comment by rahul4989** [comment]
Mastering Data Structures & Algorithms using C and C++         https://www.udemy.com/datastructurescncpp/

**Comment by rahul4989** [comment]
Node with socket.io
Build a full web chat app from scratch

https://www.udemy.com/share/100ehgBUsZeVxRRnQ=/

**Comment by namyasinha** [comment]
Node with react
https://www.udemy.com/share/1000Do/

**Comment by jeevanavegi** [comment]
Complete Python bootcamp-https://www.udemy.com/share/100058/

**Comment by td-locus-user** [comment]
Thanks for your commitment in helping us out in this regard. @UKN619 , @devanshsrivastava , @rahul4989 , @namyasinha , @jeevanavegi :)
